SELECT DISTINCT  COUNT(ID) FROM teaches
WHERE SEMESTER="SPRING" AND YEAR="2018";

SELECT COUNT(*) AS TEACHER_COUNT
FROM teaches;

SELECT DEPARTMENT, AVG(SALARY) FROM instructor
GROUP BY DEPARTMENT;

SELECT DEPARTMENT,AVG(SALARY)
FROM instructor
GROUP BY DEPARTMENT 
HAVING AVG(SALARY)>42000;



SELECT NAME 
FROM instructor
WHERE NAME NOT IN ('MOZART', 'EINSTEIN');

SELECT NAME 
FROM instructor
WHERE  SALARY > ANY (SELECT SALARY FROM instructor WHERE DEPARTMENT = 'Biology');


SELECT NAME 
FROM instructor
WHERE  SALARY > ALL (SELECT SALARY FROM instructor WHERE DEPARTMENT = 'Biology');

SELECT DEPARTMENT, AVG(SALARY) 
FROM instructor
GROUP BY DEPARTMENT
HAVING AVG(SALARY) > 42000;